name: CI/CD

on:
  push:
    branches: [ ActionGit, master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: hotel_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest requests

      - name: Build images & Start containers
        run: |
          docker compose -f docker-compose.ci.yml up -d --build

      - name: Wait for services (30 сек)
        run: sleep 30

      - name: Health checks
        run: |
          curl -f http://localhost:5000/ || exit 1
          curl -f http://localhost:5001/ || exit 1
          curl -f http://localhost:5002/ || exit 1

      - name: Run tests
        run: |
          pytest tests/test_endpoints.py -v

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/ActionGit'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/ActionGit'
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hotel-main:latest .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hotel-ai:latest ./microservices/ai_assistant
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hotel-payment:latest ./microservices/payment-service

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hotel-main:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hotel-ai:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hotel-payment:latest